# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.14.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [29]:
world = tf.constant('World')

In [30]:
result = hello + world

In [31]:
result

<tf.Tensor 'add_3:0' shape=() dtype=string>

In [32]:
type(result)

tensorflow.python.framework.ops.Tensor

In [33]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [34]:
result

b'HelloWorld'

** Computations **

In [35]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [36]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [37]:
tensor_1 + tensor_2

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [38]:
sess

In [39]:
sess.close()

## Operations

In [40]:
const = tf.constant(10)

In [41]:
fill_mat = tf.fill((4,4),10)

In [42]:
myzeros = tf.zeros((4,4))

In [43]:
myones = tf.ones((4,4))

In [44]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [45]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [23]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())#The eval function lets a Python program run Python code within itself.
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.79621243  1.0472174  -0.3208245   0.38284424]
 [ 0.18858105  0.19227076  0.09267451 -0.32952443]
 [ 0.8373032  -0.17294346 -0.12945823  0.80648744]
 [ 0.16190673 -0.32519245  0.28039175 -0.9745188 ]]


[[0.9890026  0.09414756 0.48222136 0.3354559 ]
 [0.13429952 0.78825665 0.7133615  0.32921267]
 [0.46918046 0.14981627 0.0150075  0.00994289]
 [0.9951701  0.9150828  0.5742781  0.05892253]]




## Matrix Multiplication

In [28]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [59]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [60]:
b = tf.constant([[10],[100]])

In [61]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [62]:
result = tf.matmul(a,b)

In [63]:
result.eval()

array([[210],
       [430]])

In [6]:
import numpy as np
a = np.zeros((5,5))

In [7]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])