In [7]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [61]:
import numpy as n
distance=[10,12,15,18]
time=[8,9,3,2]
d=n.array(distance)
t=n.array(time)
print(d/t)

[1.25       1.33333333 5.         9.        ]


In [21]:
a=n.array([[4,3,5],[6,5,4]])
print(a)
a.shape

[[4 3 5]
 [6 5 4]]


(2, 3)

In [5]:
import numpy as n
a=n.array([1,2,4.5,7.6])
print(a)

[1.  2.  4.5 7.6]


In [8]:
print(n.__version__)

1.16.2


In [10]:
a.dtype #type of elements

dtype('float64')

In [11]:
a.ndim #dimension

1

In [20]:
a.size #total number of elements

4

In [19]:
a.shape #it will tell the number of elements in rows

(4,)

In [26]:
a=n.array([[[2,2],[3,2]],[[3,4],[5,6]],[[5,7],[8,7]]])
a.shape

(3, 2, 2)

In [33]:
x=n.ones((3,2,2),dtype='int')
print(x)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [70]:
a=n.array([[5,6,7,8],[1,2,3,4]])
b=a[:][1]
c=a[:,[1,3]]
d=a[:,1:3]
print(b,end='#\n')
print(c,end='#\n')
print(d,end='#\n')
print(c+d) #BROADCASTING

[1 2 3 4]#
[[6 8]
 [2 4]]#
[[6 7]
 [2 3]]#
[[12 15]
 [ 4  7]]


Broadcasting
1. There should be equal no. of elemntes in both arrays
2. any one array should consist of single elements

In [71]:
a>4 #boolean comparison

array([[ True,  True,  True,  True],
       [False, False, False, False]])

Wap1: 2 3x3 Arrays and add them up. Also create a 3rd 3x3 array and multiply the entire array with 5.
Wap2: 4x4-2 dimensional array and then slice it into half horizontaly

In [74]:
#WAP1
a=n.array([[1,2,3],[4,5,6]])
b=n.array([[7,8,9],[10,11,12]])
c=n.array([[13,14,15],[16,17,18]])
print(a+b)
print(c*5)

[[ 8 10 12]
 [14 16 18]]
[[65 70 75]
 [80 85 90]]


In [78]:
#WAP2
a=n.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a[:2,:])

[[1 2 3 4]
 [5 6 7 8]]
