In [22]:
import numpy as np
from numpy import mean,array,cov
from numpy.linalg import eig

In [23]:
#define a matrix
A=np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
#calculate the mean of each column
M=mean(A.T, axis=1)
M

array([3., 4.])

In [25]:
#center columns by subtracting column means
C=A-M
C

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [26]:
#calculate covariance matrix fo centered matrix
V=cov(C.T)
V

array([[4., 4.],
       [4., 4.]])

In [27]:
#eigendecomposition of covariance matrix
values, vectors= eig(V)
print(values)
print(vectors)

[8. 0.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [28]:
P=vectors.T.dot(C.T)
P.T

array([[-2.82842712,  0.        ],
       [ 0.        ,  0.        ],
       [ 2.82842712,  0.        ]])