# Random Module

The random module provides nice functions to generate random numbers

In [2]:
#Random numbers between[0,1) of shape 2,2
import numpy as n
print(n.random.rand(3,3))

[[0.49166626 0.43253984 0.85242756]
 [0.85640842 0.89920753 0.19314001]
 [0.58005932 0.22865921 0.15557634]]


In [6]:
#Normal distribution with mean=0 and varience=1 of shape 2,2
print(n.random.randn(2,2))

[[ 1.0187285  -0.67760295]
 [-0.78778744 -1.09289737]]


In [9]:
#random integers b/w [0,10) of shape 2,2
print(n.random.randint(0,10, size=[2,2])) 

[[5 6]
 [6 3]]


In [10]:
#one random number b/w [0,1)
print(n.random.random())

0.13294418040882994


In [14]:
a=n.random.random(size=[3,3])
print(a)

[[0.7655965  0.91447428 0.61275051]
 [0.1288429  0.54869212 0.05028719]
 [0.67304828 0.32336154 0.83614784]]


In [20]:
print(a.sum())

41.0


# Shape

In [4]:
#for given input
a=n.floor(10*n.random.random((3,4)))
print(a)

[[7. 0. 6. 9.]
 [1. 6. 1. 6.]
 [1. 3. 2. 5.]]


In [18]:
a.ravel()

array([0., 5., 1., 8., 4., 2., 9., 1., 2., 1., 0., 8.])

In [25]:
a.reshape(6,2)

array([[0., 5.],
       [1., 8.],
       [4., 2.],
       [9., 1.],
       [2., 1.],
       [0., 8.]])

In [26]:
a.T

array([[0., 4., 2.],
       [5., 2., 1.],
       [1., 9., 0.],
       [8., 1., 8.]])

In [28]:
a.shape

(3, 4)

In [29]:
a.resize((2,6))

In [30]:
print(a)

[[0. 5. 1. 8. 4. 2.]
 [9. 1. 2. 1. 0. 8.]]


In [31]:
a.shape

(2, 6)

In [34]:
a=n.array([10,20,20])
ap=n.floor(a)
ap

array([10., 20., 20.])

# pi module

In [36]:
from numpy import pi
n.cos(0)

1.0

In [72]:
i=n.random.normal(27000,15000,1000)
print(i)

[ 34766.65545266  12662.76689291  26857.50352451  52828.52746743
  -4688.16044752  20172.80226708  21473.21798371  22807.49924276
   7206.0319804   20376.82691983  22067.68509977  15418.62290766
  21637.04182813  23837.20876064  61310.05355326  13452.02897065
   6386.53421246  16372.89374251  52328.55944671  34453.84159772
  31822.20911823  20622.54051196  13954.02031917  42788.5013939
  39297.59811147   8912.79378524  35098.92302871  42312.19975107
  16255.25387221  33989.26152927  41010.43330403  43100.42052699
  10318.70734173  41837.02956775  35049.78275994  -7820.7720165
  66384.07621083  20450.65592894  19311.50060168   -479.04224685
   3127.59622821  36385.56355592  30699.47223363  14241.37450053
  18140.2335949   52302.36925963  -9064.07070937  60440.38776984
  47805.01876192  27902.18502693  51277.57569657  50831.76643436
  23259.55289126  11370.6415992   28648.57686718 -12412.65302401
  13507.63970926  23370.76949984 -14613.63987693  24955.53468411
   3158.144504      308.981

In [66]:
print(n.mean(i))
print(n.median(i))

128105.43249802264
27169.930278787695


In [48]:
print(i.std())

15100.705376699889


In [52]:
i=n.append(i,[100000000])

In [53]:
print(n.mean(i))
print(n.median(i))

128105.43249802264
27169.930278787695


In [57]:
from scipy import stats

In [70]:
stats.mode(i)

ModeResult(mode=array([-15931.83003792]), count=array([1]))

outlier