 Exploratory Data Analysis refers to the critical process of performing initial investigations on data so as to discover patterns,to spot anomalies,to test hypothesis and to check assumptions with the help of summary statistics and graphical representations.



# Quick Recap: Lists
Collection of values
Multiple types (heterogeneous)
Add, remove, update
List
A list is a collection of values. You can individually add, remove, or update these values. A single list can contain multiple data types.

In [1]:
distance = [12,44,54,70,50]
time = [0.27,0.54,0.77,0.55,0.29]

In [2]:
speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

# Why NumPy
Import NumPy
Create “distance” and “time” NumPy arrays
Mathematical function applied over the entire “distance” and “time” arrays
Output
Numerical Python (NumPy) supports multidimensional arrays over which you can easily apply mathematical operations.

 Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [4]:
import numpy as np

In [29]:
print(np.__version__)

1.16.2


In [31]:
x = np.array([1,2,3,7.8,6.7])
x


array([1. , 2. , 3. , 7.8, 6.7])

In [5]:
type(x)

numpy.ndarray

In [5]:
x1 = np.array([1,2,3])

In [7]:
a = (1,3,5)
b = np.array(a)
b

array([1, 3, 5])

In [1]:
import numpy as np

In [10]:
z = np.array(1)

In [11]:
z

array(1)

In [32]:
print(b)
type(b)

[1 3 5]


numpy.ndarray

In [174]:
distance1 = np.array(distance)
time1 = np.array(time)

In [7]:
type(distance)

list

In [8]:
type(distance1)

numpy.ndarray

In [9]:
speed = distance1/time1

In [10]:
speed

array([ 44.44444444,  81.48148148,  70.12987013, 127.27272727,
       172.4137931 ])

In [12]:
type(speed)

numpy.ndarray

To summarise, the main differences with python lists are:

1.Arrays support vectorised operations, while lists don’t.
2.Once an array is created, you cannot change its size. You will have to create a new array or overwrite the existing one.
3.Every array has one and only one dtype. All items in it should be of that dtype.
4.An equivalent numpy array occupies much less space than a python list of lists.

# Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [8]:
import numpy as np
arr1 = np.array([2,3,4])
arr1

array([2, 3, 4])

In [1]:
import numpy as np
x = np.array([1,2,3,"abc"])

In [2]:
x

array(['1', '2', '3', 'abc'], dtype='<U11')

In [16]:
arr2 = np.array([1.2, 3.5, 5.1])
arr2

array([1.2, 3.5, 5.1])

In [18]:
arr3 = np.array(["abc","def"])
arr3
#arr3.dtype

array(['abc', 'def'], dtype='<U3')

In [19]:
arr4 = np.array(["xyz","ijk"])

In [8]:
#A frequent error consists in calling array with multiple numeric arguments, rather than #providing a single list of numbers as an argument.
#a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT



array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [9]:
x = np.array([(1,2,3),(4,5,6)])

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
x.ndim

2

In [61]:
b = np.array([[[(1.5,2,3), (4,5,6),(7,8,9)]]])
b

array([[[[1.5, 2. , 3. ],
         [4. , 5. , 6. ],
         [7. , 8. , 9. ]]]])

In [62]:
b.ndim

4

In [63]:
b.shape

(1, 1, 3, 3)

In [64]:
b.ndim

4

In [51]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [32]:
x = np.ones( (2,4,4), dtype=np.int16 ) #2=no.of arrays    

In [33]:
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [34]:
x.ndim

3

In [35]:
x.shape

(2, 4, 4)

In [36]:
d= np.array([[[1,2],[3,4,5],[6,7,8,9]]])
d
#d.shape


array([[list([1, 2]), list([3, 4, 5]), list([6, 7, 8, 9])]], dtype=object)

# Class and Attributes of ndarray—.ndim
Numpy’s array class is “ndarray,” also referred to as “numpy.ndarray.” The attributes of ndarrayare:

This refers to the number of axes (dimensions) of the array. It is also called the rank of the array.

In [8]:
import numpy as np 
a = np.array(1) 
print (a)

1


In [9]:
a.ndim

0

In [3]:
x = np.array([1,2,3])

In [4]:
x.ndim

1

In [37]:
# more than one dimensions 
b = np.array([[1, 2,5], [3, 4,7]])
print (b)
b.ndim


[[1 2 5]
 [3 4 7]]


2

In [6]:
#b = np.array([[[1, 2,4,5], [3, 4,5,6]]])
#print(b)

In [7]:
b.ndim

2

# ndarray.shape

This consists of a tuple of integers showing the size of the array in each dimension. The length of the “shape tuple” is the rank or ndim.


In [38]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

# ndarray.size

It gives the total number of elements in the array. It is equal to the product of the elements of the shape tuple.

In [40]:
a.size

3

In [41]:
b.size

6

In [13]:
import numpy as np 
b = np.array([[[1, 2], [3, 4]]])
           

In [14]:
b

array([[[1, 2],
        [3, 4]]])

In [15]:
b.ndim

3

In [16]:
b.shape

(1, 2, 2)

In [17]:
b.astype("float")

array([[[1., 2.],
        [3., 4.]]])

In [18]:
b.astype('int')

array([[[1, 2],
        [3, 4]]])

In [19]:
b.astype('str')

array([[['1', '2'],
        ['3', '4']]], dtype='<U11')

# ndarray.dtype 

It’s an object that describes the type of the elements in the array. It can be created or specified using Python.

In [16]:
b.dtype

dtype('int32')

In [17]:
a.itemsize #its32bitint so 32/8 = 4

4

In [18]:
b.itemsize

4

Let’s suppose you were handed a numpy vector that you didn’t create yourself. What are the things you would want to explore in order to know about that array?

Well, I want to know:

#If it is a 1D or a 2D array or more. (ndim)

#How many items are present in each dimension (shape)

#What is its datatype (dtype)

#What is the total number of items in it (size)

#Samples of first few items in the array (through indexing)

numpy arrays support boolean indexing.

A boolean index array is of the same shape as the array-to-be-filtered and it contains only True and False values. The values corresponding to True positions are retained in the output.

In [20]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [21]:
arr2>4

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

# Basic Operations—Example
NumPy uses the indices of the elements in each array to carry out basic operations. In this case, where we are looking at a dataset of four cyclists during two trials, vector addition of the arrays gives the required output.

In [20]:
np_first_trial_cyclist = np.array([10,12,15,16])

In [21]:
np_second_trial_cyclist = np.array([20,25,30,45])

In [22]:
np_first_trial_cyclist + np_second_trial_cyclist

array([30, 37, 45, 61])

# Accessing Array Elements: Indexing
You can access an entire row of an array by referencing its axis index.

In [79]:
import numpy as np
cyclist_trial = np.array([[10,12,15,16],[20,25,30,45]])
cyclist_trial

array([[10, 12, 15, 16],
       [20, 25, 30, 45]])

In [84]:
first_trial = cyclist_trial[0]

In [85]:
first_trial

array([10, 12, 15, 16])

In [86]:
second_trial = cyclist_trial[1]
second_trial

array([20, 25, 30, 45])

# Accessing Array Elements: Indexing (contd.)
You can refer the indices of the elements in an array to access them. You can also select a particular index of more than one axis

In [94]:
cyclist_trial

array([[10, 12, 15, 16],
       [20, 25, 30, 45]])

In [20]:
first_trial = cyclist_trial[1][0] #secondrow,first column

In [21]:
first_trial

20

In [22]:
a = cyclist_trial[1,1]
a

25

In [25]:
second_trial = cyclist_trial[:,2]
second_trial

array([15, 30])

In [26]:
cyclist_trial.shape

(2, 4)

array([[10, 12, 15, 16],
       [20, 25, 30, 45]])

In [29]:
third_trial = cyclist_trial[:,1:3]

In [30]:
third_trial

array([[12, 15],
       [25, 30]])

In [41]:
s = slice(1)
print(a[s])

[10]


In [46]:
a = ("a","b","c","d","e","f","g","h")
x = slice(4,6)
print(a[x])

('e', 'f')


In [104]:
b = np.arange(2.5,6.5)

In [105]:
b

array([2.5, 3.5, 4.5, 5.5])

In [42]:
# slice single item 
a = np.arange(10) 
b = a[5] 
print (b)

5


In [8]:
x = np.arange(10,21)
print(x)

[10 11 12 13 14 15 16 17 18 19 20]


In [108]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [110]:
a[0:6:2] = -1000 
a         # equivalent to a[0:6:2] = -1000; from start to position 0, exclusive, set every 2nd element to -1000

array([-1000,     1, -1000,     9, -1000,    25,    36,    49,    64,
          81], dtype=int32)

In [48]:
# slice items starting from index 
a = np.arange(10)
print(a)
print (a[2:])


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [116]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print( a ) 
a.ndim
## slice items starting from index
#print ('Now we will slice the array from the index a[1:]') 
print (a[1:])
print (a[1][1])
print (a[1][1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]
4
[4 5]


In [16]:
a=np.array([[1,2,3,4,5],[1,2,4,78,8,],[3,6,8,4,3],([1,2,4],[2,3,4,4])])
print(a[2:])
print(a[:1])
print(a[0:])
a.ndim


[list([3, 6, 8, 4, 3]) ([1, 2, 4], [2, 3, 4, 4])]
[list([1, 2, 3, 4, 5])]
[list([1, 2, 3, 4, 5]) list([1, 2, 4, 78, 8]) list([3, 6, 8, 4, 3])
 ([1, 2, 4], [2, 3, 4, 4])]


1

In [23]:
#The random module provides nice functions to generate random numbers (and also statistical distributions) of any given shape.

# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

# One random number between [0,1)
print(np.random.random())

# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))



[[0.09318509 0.76146703]
 [0.70461284 0.67871204]]
[[0.51617916 0.89222427]
 [0.23728491 0.55572341]]
[[6 0]
 [7 4]]
0.4643672437202171
[[0.67418712 0.35735459]
 [0.06893541 0.58864526]]


return random floats in half open interval[0.0,1.0)

In [12]:
import numpy as np
np.random.random_sample((5,))

array([0.17931546, 0.65452697, 0.75930669, 0.9666099 , 0.8627508 ])

In [33]:
type(np.random.random_sample())

float

In [120]:
a = np.random.random([3,3]) #indices(no.ofrows,no.columns)
a

array([[0.83061799, 0.59387408, 0.70084253],
       [0.80556457, 0.89698446, 0.60324668],
       [0.44783732, 0.61015597, 0.07551701]])

In [127]:
c = a.sum()
c

5.564640609109634

In [134]:
x = np.arange(20).reshape(5, 4)
#row, col = np.indices((2, 3))
#x[row, col]
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [139]:
row, col = np.indices((3, 2))
x[row, col]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [123]:
a.min()

0.07551700556949725

In [11]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
b[2][1]

9

In [13]:
b.sum()

66

In [8]:
b.sum(axis=0 ) #sum across column

array([12, 15, 18, 21])

In [15]:
b.sum(axis=1) #sum across rows#R1

array([ 6, 22, 38])

In [38]:
A = np.array( [[1,1],
             [0,1]] )
B = np.array( [[2,0],
             [3,4]] )

In [39]:
type(A)

numpy.ndarray

In [40]:
A*B   #Elementwise product

array([[2, 0],
       [0, 4]])

In [41]:
A@B  #MatrixMultipication

array([[5, 4],
       [3, 4]])

In [26]:
A.dot(B)   #Another matrix multipication

array([[5, 4],
       [3, 4]])

# Shape Manipulation¶

In [1]:
#Changing the shape of an array

#An array has a shape given by the number of elements along each axis:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
a

array([[6., 0., 4., 2.],
       [1., 0., 4., 2.],
       [1., 5., 2., 6.]])

In [2]:
a.shape

(3, 4)

In [3]:
#The shape of an array can be changed with various commands.
#Note that the following three commands all return a modified array, but do not change the original array:

a.ravel() #flatened array

array([6., 0., 4., 2., 1., 0., 4., 2., 1., 5., 2., 6.])

In [4]:
a.shape

(3, 4)

In [12]:
 a = a.reshape(6,2)

In [14]:
a

array([[6., 0.],
       [4., 2.],
       [1., 0.],
       [4., 2.],
       [1., 5.],
       [2., 6.]])

In [13]:
 a.T #Transpose:value of row changes to column

array([[6., 4., 1., 4., 1., 2.],
       [0., 2., 0., 2., 5., 6.]])

In [7]:
a

array([[6., 0., 4., 2.],
       [1., 0., 4., 2.],
       [1., 5., 2., 6.]])

In [8]:
a.shape

(3, 4)

In [9]:
#The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:
a

array([[6., 0., 4., 2.],
       [1., 0., 4., 2.],
       [1., 5., 2., 6.]])

In [10]:
a.resize((2,6))
a

array([[6., 0., 4., 2., 1., 0.],
       [4., 2., 1., 5., 2., 6.]])

In [11]:
a.shape

(2, 6)

# Universal Functions (ufunc)
NumPy provides useful mathematical functions called Universal Functions. These functions operate element-wise on an array, producing another array as output.

In [37]:
np_sqrt =np.sqrt([2,4,9,16])

In [38]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [16]:
from numpy import pi
np.cos(0)

1.0

In [17]:
np.sin(pi/2)

1.0

In [18]:
np.sin(90)

0.8939966636005579

In [19]:
np.cos(pi)

-1.0

In [20]:
pi

3.141592653589793

In [50]:
np.floor([1.2,1.6,2.7,3.3,-0.3,-1.4])

array([ 1.,  1.,  2.,  3., -1., -2.])

In [49]:
np.sin(90 * np.pi / 180)


1.0

# creating array from existing array

In [21]:
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print (a)


[1 2 3]


In [89]:
# dtype is set 
a = np.asarray(x, dtype = float) 
print (a)

[ 1.  2.  3.]


In [14]:
# ndarray from tuple 

x = (1,2,3) 
a = np.asarray(x) 
print (a)


[1 2 3]


In [15]:
m = a

In [16]:
type(m)

numpy.ndarray

In [28]:
type(a)

numpy.ndarray

In [59]:
# ndarray from list of tuples 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)


[(1, 2, 3) (4, 5)]


In [5]:
import numpy as np 
x = np.arange(5) 
print (x)

[0 1 2 3 4]


In [6]:
# dtype set 
x = np.arange(5, dtype = float)
print (x)


[ 0.  1.  2.  3.  4.]


In [39]:
# start and stop parameters set 
x = np.arange(10,20) 
print (x)


[10 11 12 13 14 15 16 17 18 19]


In [25]:
import numpy as np 
x = np.linspace(10,20,4) 
print (x)


[10.         13.33333333 16.66666667 20.        ]


In [24]:
import numpy as np 
x = np.linspace(10,20,10) 
print (x)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [9]:
# endpoint set to false 
x = np.linspace(10,20, 5, endpoint = False) 
print (x)


[10. 12. 14. 16. 18.]


# Broadcasting
NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method, NumPy automatically broadcasts the smaller array over the larger array.

In [168]:

import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30]) 
c = a * b 
print (c)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [172]:
a = np.array([5])
a

array([5])

In [173]:
d = a * b
print (d)
type(d)


[ 50 100 150]


numpy.ndarray

Though broadcasting can help carry out mathematical operations between different-shaped arrays, they are subject to certain constraints as listed below:
•When NumPy operates on two arrays, it compares their shapes element-wise. It finds these shapes compatible only if:
•Their dimensions are the same or
•One of them has a dimension of size 1.
•If these conditions are not met, a "ValueError” is thrown, indicating that the arrays have incompatible shapes.# 

In [170]:
e = np.array([4,5,6,7])
print(e)

[4 5 6 7]


In [171]:
f = d*e
f

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [96]:
f = e*7
print(f)

[28 35 42 49]


# Question

Create 2 - 3 X 3 Arrays and add them up. Also create a 3rd 3x3 array and multiply the entire array with 5.

Create a 4x4 - 2 dimensional array and then slice it into half horizontally.

In [8]:
import numpy as np
a = np.array([1,2.5,True,"sal"])

In [9]:
a

array(['1', '2.5', 'True', 'sal'], dtype='<U32')

# Identy matrics

In [4]:
a=np.eye(2,2)
a

array([[1., 0.],
       [0., 1.]])